---
- name: Installs python application on server (secret gen, db setup, nginx and uwsgi config)
  hosts: all

  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../src"
    ansible_python_interpreter: /mnt/persist/www/django/env/bin/python

  tasks:
    - name: Generates secrets/passwords
      set_fact:
        secret_key: "{{ lookup('password', '/dev/null chars=ascii_letters length=80') }}"
        database_password: "{{ lookup('password', '/dev/null chars=ascii_letters length=40') }}"

    - name: Count previous uwsgi apps
      shell: ls -1 /mnt/persist/uwsgi/conf.d/ | wc -l
      register: uwsgi_application_count

    - name: Makes sure python psql lib is available
      pip:
        name: psycopg2-binary
        virtualenv: /mnt/persist/www/django/env
        virtualenv_python: python3

    - name: Creates directory for shared files
      file:
        path: "{{ ansistrano_deploy_to }}/shared"
        state: directory
        owner: www-data
        group: www-data
        mode: 0775
        recurse: yes

    - name: Creates application configuration
      copy:
        src: "files/example.env"
        dest: "{{ ansistrano_deploy_to }}/shared/.env"
        owner: www-data
        group: www-data
        mode: 0644

    - replace:
        path: "{{ ansistrano_deploy_to }}/shared/.env"
        regexp: 'SECRET_KEY=(.*)$'
        replace: 'SECRET_KEY={{ secret_key }}'

    - replace:
        path: "{{ ansistrano_deploy_to }}/shared/.env"
        regexp: 'DATABASE_PASSWORD=(.*)$'
        replace: 'DATABASE_PASSWORD={{ database_password }}'

    - replace:
        path: "{{ ansistrano_deploy_to }}/shared/.env"
        regexp: 'DJANGO_SETTINGS_MODULE=(.*)$'
        replace: 'DJANGO_SETTINGS_MODULE=core.settings.{{ stage_name }}'

    - name: Creates postgres database
      postgresql_db:
        name: "{{ database_name }}"

    - name: Creates postgres user
      postgresql_user:
        db: "{{ database_name }}"
        name: "{{ database_user }}"
        password: "{{ database_password }}"
        priv: ALL

    - name: Copies uWSGI config
      copy:
        src: "files/uwsgi.ini"
        dest: "/mnt/persist/uwsgi/conf.d/{{ project_slug }}.ini"
        mode: 0644

    - replace:
        path: "/mnt/persist/uwsgi/conf.d/{{ project_slug }}.ini"
        regexp: 'UWSGI_STATS_PORT'
        replace: '{{ 9190+(uwsgi_application_count.stdout|int) }}'

    - name: Copies nginx config
      copy:
        src: "files/nginx.conf"
        dest: "/mnt/persist/nginx/conf.d/{{ project_slug }}.conf"
        mode: 0644

- name: Run deploy playbook
  import_playbook: deploy.yml



