version: '3'
services:
  python:
    image: frojd/wagtail_pipit_web
    build: ./src
    volumes:
      - "./src:/app"
    depends_on:
      - db
    env_file: ./docker/config/web.env

  db:
    image: postgis/postgis:12-2.5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
