version: '3'
services:
  web:
    image: frojd/django_boilerplate_web
    build: ./src
    ports:
      - "8081:8000"
    depends_on:
      - db
    environment:
      - REQUIREMENTS=local.txt
    env_file: ./docker/config/web.env
  frontend:
    image: frojd/django_boilerplate_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app:cached"
      - "./src:/webapp:cached"
    ports:
      - "8082:3000"
  db:
    image: mdillon/postgis:10
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
