{% raw -%}
- name: Create .env file
  file:
    path: "{{ansistrano_shared_path}}/.env"
    state: touch
    mode: 0775

- name: Create media dir
  file:
    path: "{{ansistrano_shared_path}}/media"
    owner: deploy
    group: www-data
    state: directory
    mode: 0775

- name: Create logs dir
  file:
    path: "{{ ansistrano_deploy_to }}/logs"
    owner: deploy
    group: www-data
    state: directory
    mode: 0775
{% endraw %}
