{% raw -%}
- name: Create cache table
  shell: "{{ ansistrano_shared_path }}/venv/bin/python {{ ansistrano_release_path.stdout }}/src/manage.py createcachetable"

- name: Collect static
  shell: "{{ ansistrano_shared_path }}/venv/bin/python {{ ansistrano_release_path.stdout }}/src/manage.py collectstatic --noinput"

- name: Make sure deploy:www-data has ownership of current
  file:
    path: "{{ item }}"
    owner: deploy
    group: www-data
    state: directory
    recurse: yes
  with_items:
    - "{{ ansistrano_deploy_to }}/current"
    - "{{ ansistrano_deploy_to }}/logs"

- name: Restart uWSGI
  service:
    name: uwsgi
    state: restarted

- name: Restart pm2
  shell: "pm2 stop {{ ansistrano_shared_path }}/pm2/{{ project_slug }}.yml || true && pm2 start {{ ansistrano_shared_path }}/pm2/{{ project_slug }}.yml"

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

{% endraw %}
