{% raw -%}
- name: Create cache table
  shell: "{{ ansistrano_shared_path }}/venv/bin/python3 {{ ansistrano_release_path.stdout }}/src/manage.py createcachetable"

- name: Collect static
  shell: "{{ ansistrano_shared_path }}/venv/bin/python {{ ansistrano_release_path.stdout }}/src/manage.py collectstatic --noinput"

- name: Symlink app
  file:
    src: "{{ ansistrano_release_path.stdout }}/src"
    dest: "{{ public_path }}"
    state: link
  when: public_path is defined

- name: Restart uWSGI
  service:
    name: uwsgi
    state: restarted

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
{% endraw %}
