{% raw -%}

---
- name: Installs python application on server (secret gen, db setup, nginx and uwsgi config)
  hosts: all

  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../src"

  tasks:
    - name: Generates secrets/passwords
      set_fact:
        secret_key: "{{ lookup('password', '/dev/null chars=ascii_letters length=80') }}"
        database_password: "{{ lookup('password', '/dev/null chars=ascii_letters length=40') }}"

    - name: Counts previous uwsgi apps
      shell: ls -1 /mnt/persist/uwsgi/conf.d/ | wc -l
      register: uwsgi_application_count

    - name: Makes sure python psql lib is available
      pip:
        name: psycopg2-binary

    - name: Creates directory for shared files
      file:
        path: "{{ ansistrano_deploy_to }}/shared"
        state: directory
        owner: www-data
        group: www-data
        mode: 0775
        recurse: yes

    - name: Create .env file
      template:
        src: files/.env.j2
        dest: "{{ ansistrano_deploy_to }}/shared/.env"
        owner: www-data
        group: www-data
        mode: 0644

    - name: Creates postgres database
      postgresql_db:
        name: "{{ database_name }}"

    - name: Creates postgres user
      postgresql_user:
        db: "{{ database_name }}"
        name: "{{ database_user }}"
        password: "{{ database_password }}"
        priv: ALL

    - name: Creates uWSGI config
      template:
        src: files/uwsgi.ini.j2
        dest: "/mnt/persist/uwsgi/conf.d/{{ project_slug }}.ini"
        mode: 0644

    - name: Replaces default uwsgi conf with empty
      file:
        path: "/mnt/persist/uwsgi/conf.d/django.ini"
        state: absent

    - shell: echo "" > /mnt/persist/uwsgi/conf.d/django.ini

    - name: Copies nginx config
      copy:
        src: "files/nginx.conf"
        dest: "/mnt/persist/nginx/conf.d/{{ project_slug }}.conf"
        mode: 0644

    - name: Copies robots.txt
      copy:
        src: "files/robots.txt"
        dest: "{{ ansistrano_deploy_to }}/shared/robots.txt"
        owner: www-data
        group: www-data
        mode: 0644

    - name: Creates directory for ssr files
      file:
        path: "{{ ansistrano_deploy_to }}/shared/ssr"
        state: directory
        owner: www-data
        group: www-data
        mode: 0775
        recurse: yes

    - name: Create ssr_config.yml file
      template:
        src: files/ssr_config.yml.j2
        dest: "{{ ansistrano_deploy_to }}/shared/ssr/{{ project_slug }}.yml"
        owner: www-data
        group: www-data
        mode: 0644

- name: Runs deploy playbook
  import_playbook: deploy.yml

{% endraw %}
