webservers:
  hosts:
    stage1:
      ansible_user: deploy
      ansible_port: 22
      ansible_host: {{ cookiecutter.ssh_host_stage }}
      domain: {{ cookiecutter.domain_stage }}
      stage_name: stage
