version: '2'
services:
    db:
        # For postgres with postgis use this
        # image: mdillon/postgis:9.5
        image: postgres:9.5
        ports:
            - "{{cookiecutter.docker_db_port}}:5432"
        volumes:
            - "./docker/files/db-dumps/:/docker-entrypoint-initdb.d/"
            - "./docker/files/shared:/shared:rw"
        env_file: ./docker/config/db.env
    web:
        image: frojd/{{cookiecutter.project_slug}}_web
        build: ./src
        volumes:
            - "./src:/app"
            - "./docker/files/shared:/shared:rw"
            - "./docker/files/var/log:/var/log:rw"
        ports:
            - "{{cookiecutter.docker_web_port}}:8000"
        depends_on:
            - db
        environment:
            RUN_TYPE: "runserver"
            REQUIREMENTS: "local.txt"
        env_file: ./docker/config/web.env
