version: '3'
services:
    web:
        image: frojd/{{cookiecutter.project_slug}}_web
        build: ./src
        volumes:
            - "./src:/app"
            - "./docker/files/shared:/shared:rw"
            - "./docker/files/var/log:/var/log:rw"
        ports:
            - "{{cookiecutter.docker_web_port}}:8000"
        depends_on:
            - db
        environment:
            REQUIREMENTS: "local.txt"
        env_file: ./docker/config/web.env
    db:
        {%- if cookiecutter.use_geodjango == 1 -%}
        image: mdillon/postgis:9.6
        {% else %}
        image: postgres:9.6
        {% endif -%}
        ports:
            - "{{cookiecutter.docker_db_port}}:5432"
        volumes:
            - "./docker/files/db-dumps/:/docker-entrypoint-initdb.d/"
            - "./docker/files/shared:/shared:rw"
        env_file: ./docker/config/db.env
