version: "3.1"
services:
  python:
    image: frojd/{{cookiecutter.project_slug}}_web
    build: ./src
    volumes:
      - "./src:/app"
    depends_on:
      - db
    env_file: ./docker/config/web.env

  web:
    image: nginx:alpine
    working_dir: /app
    ports:
      - "{{cookiecutter.docker_web_port}}:80"
      - "{{cookiecutter.docker_web_ssl_port}}:443"
    links:
      - python
    volumes:
      - "./docker/files/config/nginx.conf.template:/etc/nginx/templates/default.conf.template:cached"
      - "./docker/files/certs:/etc/nginx/certs"
      - "./src/media:/app/media"
      - "./src/static:/app/static"
    environment:
      - PYTHON_HOST=http://python:8000

  db:
    image: postgis/postgis:12-2.5
    ports:
      - "{{cookiecutter.docker_db_port}}:5432"
    volumes:
      - "./docker/files/db-dumps/:/docker-entrypoint-initdb.d/"
      - "./docker/files/shared:/shared:rw"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
