version: "3.1"
services:
  python:
    image: frojd/company_project_web
    build: ./src
    volumes:
      - "./src:/app"
    depends_on:
      - db
    env_file: ./docker/config/web.env

  web:
    image: nginx:alpine
    working_dir: /app
    ports:
      - "8081:80"
    links:
      - python
    volumes:
      - "./docker/files/config/nginx.conf:/etc/nginx/conf.d/default.conf:cached"
      - "./src/media:/app/media"
      - "./src/static:/app/static"

  db:
    image: postgis/postgis:12-2.5
    ports:
      - "8082:5432"
    volumes:
      - "./docker/files/db-dumps/:/docker-entrypoint-initdb.d/"
      - "./docker/files/shared:/shared:rw"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
