- name: Create cache table
  shell: "{{ ansistrano_shared_path }}/venv/bin/python {{ ansistrano_release_path.stdout }}/src/manage.py createcachetable"

- name: Collect static
  shell: "{{ ansistrano_shared_path }}/venv/bin/python {{ ansistrano_release_path.stdout }}/src/manage.py collectstatic --noinput"

- name: Make sure www-data has ownership of current
  file:
    path: "{{ ansistrano_deploy_to }}/current"
    owner: www-data
    group: www-data
    state: directory
    recurse: yes

- name: Restart uWSGI
  service:
    name: uwsgi
    state: restarted

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

